# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)



User.create(username: "admin", password: "password")
show1 = Show.create(title: "Nature", description: "Nature in its element")
show2 = Show.create(title: "Humans", description: "Humans being humans")
show3 = Show.create(title: "Cities", description: "Citites around the world are examined")
show4 = Show.create(title: "Cats", description: "Cats of the world")
episode1 = Episode.create(show_id: 1, title: "Waves", description: "Waves crash on a beach", episode_number: 1)
episode2 = Episode.create(show_id: 1, title: "Milky Way", description: "A time lapse of the milky way", episode_number: 2)
episode3 = Episode.create(show_id: 1, title: "Forest", description: "An indepth look at the top of a forest", episode_number: 3)
episode4 = Episode.create(show_id: 1, title: "Mountain", description: "Wild flowers on Mt Ranier", episode_number: 4)
episode5 = Episode.create(show_id: 2, title: "Running", description: "A child runs through flags", episode_number: 1)
episode6 = Episode.create(show_id: 2, title: "Walking", description: "Humans walk across cross walk", episode_number: 2)
episode7 = Episode.create(show_id: 2, title: "Eye", description: "Close up of a human eye", episode_number: 3)
episode8 = Episode.create(show_id: 3, title: "Bangkok", description: "Slow pan of Bangkok skyline", episode_number: 1)
episode9 = Episode.create(show_id: 3, title: "Rome", description: "Rome in the evening", episode_number: 2)
episode10 = Episode.create(show_id: 3, title: "New York", description: "Grand central terminal", episode_number: 3)
episode11 = Episode.create(show_id: 4, title: "Cat in the Sun", description: "Cat Enjoys some sun", episode_number: 1)
episode12 = Episode.create(show_id: 4, title: "Danger Cat", description: "Cat hisses", episode_number: 2)
movie1 = Movie.create(title: "The Projector", description:"This sundance fetival winning film reverses everything you know about how to watch a movie")
show1.photo.attach(io: File.open("/Users/aa/Documents/videos/image/nature_waves.jpg"), filename: "waves.jpg")
show2.photo.attach(io: File.open("/Users/aa/Documents/videos/image/humans_running.jpg"), filename: "human_running.jpg")
show3.photo.attach(io: File.open("/Users/aa/Documents/videos/image/nature_ranier.jpg"), filename: "nature_ranier.jpg")
show4.photo.attach(io: File.open("/Users/aa/Documents/videos/image/cat_sun.jpg"), filename: "cat_sun.jpg")
episode1.photo.attach(io: File.open("/Users/aa/Documents/videos/image/nature_waves.jpg"), filename: "waves.jpg")
episode2.photo.attach(io: File.open("/Users/aa/Documents/videos/image/nature_milkyway.jpg"), filename: "nature_milkyway.jpg")
episode3.photo.attach(io: File.open("/Users/aa/Documents/videos/image/nature_forest.jpg"), filename: "epinature_forest.jpg")
episode4.photo.attach(io: File.open("/Users/aa/Documents/videos/image/nature_ranier.jpg"), filename: "ranier.jpg")
episode5.photo.attach(io: File.open("/Users/aa/Documents/videos/image/humans_running.jpg"), filename: "humans_running.jpg")
episode6.photo.attach(io: File.open("/Users/aa/Documents/videos/image/humans_walking.jpg"), filename: "humans_walking.jpg")
episode7.photo.attach(io: File.open("/Users/aa/Documents/videos/image/human_eye.jpg"), filename: "human_eye.jpg")
episode8.photo.attach(io: File.open("/Users/aa/Documents/videos/image/cities_bangkok.jpg"), filename: "cities_bangkok.jpg")
episode9.photo.attach(io: File.open("/Users/aa/Documents/videos/image/cities_rome.jpg"), filename: "cities_rome.jpg")
episode10.photo.attach(io: File.open("/Users/aa/Documents/videos/image/cities_grandcentral.jpg"), filename: "cities_grandcentral.jpg")
episode11.photo.attach(io: File.open("/Users/aa/Documents/videos/image/cat_sun.jpg"), filename: "cat_sun.jpg")
episode12.photo.attach(io: File.open("/Users/aa/Documents/videos/image/cat_hissing.jpg"), filename: "cat_hissing.jpg")
movie1.photo.attach(io: File.open("/Users/aa/Documents/videos/image/movie_projector.jpg"), filename: "movie_projector.jpg")
episode1.video.attach(io: File.open("/Users/aa/Documents/videos/nature_waves.webm"), filename: "waves.webm")
episode2.video.attach(io: File.open("/Users/aa/Documents/videos/nature_milkyway.webm"), filename: "nature_milkyway.webm")
episode3.video.attach(io: File.open("/Users/aa/Documents/videos/nature_forest.webm"), filename: "epinature_forest.webm")
episode4.video.attach(io: File.open("/Users/aa/Documents/videos/nature_ranier.webm"), filename: "nature_ranier.webm")
episode5.video.attach(io: File.open("/Users/aa/Documents/videos/humans_running.webm"), filename: "humans_running.webm")
episode6.video.attach(io: File.open("/Users/aa/Documents/videos/humans_walking.webm"), filename: "humans_walking.webm")
episode7.video.attach(io: File.open("/Users/aa/Documents/videos/human_eye.webm"), filename: "human_eye.webm")
episode8.video.attach(io: File.open("/Users/aa/Documents/videos/cities_bangkok.webm"), filename: "cities_bangkok.webm")
episode9.video.attach(io: File.open("/Users/aa/Documents/videos/cities_rome.webm"), filename: "cities_rome.webm")
episode10.video.attach(io: File.open("/Users/aa/Documents/videos/cities_grandcentral.webm"), filename: "cities_grandcentral.webm")
episode11.video.attach(io: File.open("/Users/aa/Documents/videos/cat_sun.webm"), filename: "cat_sun.webm")
episode12.video.attach(io: File.open("/Users/aa/Documents/videos/cat_hissing.webm"), filename: "cat_hissing.webm")
movie1.video.attach(io: File.open("/Users/aa/Documents/videos/movie_projector.webm"), filename: "movie_projector.webm")